### ISSUE TITLE
Entity structure usage

### ISSUE THREAD

**Issue by eikofee** [Echoffee/nene-quest#2]
The `Entity` structure is widely implicitly used in the project, yet it feels *really* underused. For example, the `Game` class that is being rewritten right now is using 5 different vectors of objects using the `Entity` class, and the piece of code (replace `<V>` with any of the vector variables)
```cpp
for (unsigned int i = 0; i < <V>.size(); i++) {
	<V>.at(i)->update(elapsedTime);
	if (<V>.at(i)->isDead()) {
		delete(<V>.at(i));
		<V>.erase(<V>.begin() + i);
	}
}
```
is used 4 times consecutively on the vectors except for the `Player` one.
This is only an example of factorisation that could be done is the project.

Why not put all of the entities in only one vector and checking their sub-type when needed ?

**Comment by engboris** [comment]
I think that's what Hokomokopo wanted to do but as far as I know there aren't any good mechanism to check the sub-type in C++. Do you have a particular idea in mind ?

It depends on what we do with these vectors. Maybe method masking / method redefinition in subclasses will work.

**Comment by eikofee** [comment]
Each entity should at least have an `update` and a `isDead` method in order to be manageable by `Game` without thinking too much about it, and maybe another one to check collisions between them. And since some of these entities need to know the game room's size and the position of other , `Game` could need a few new static properties.

For the sub-type identification, an enum should do the job.

That's only a guess, since the code is kinda hard to alter right now, so the `Entity` and `Game` classes may need more changes.

**Comment by eikofee** [comment]
So, from what I saw :
- For the `Enemy` class 
```
Enemy < MovableEntity < Entity
      < LivingEntity 
```
`MovableEntity` enables movement on `Entity` and nothing else.
`LivingEntity` enables hp count on any object.
So I guess I'm going to set the hp counting in `Enemy` and the movement stuff in `Entity`.

-------------------

- For the `Bonus` class
```
Bonus < MovableEntity < Entity
```
Same thing as for `Enemy`

-------------------

- For the `Weapon` class
```
Weapon < Entity
```
And `Weapon` has its own movement management in it, instead of using `MovableEntity` :thinking:


@hokolomopo am I correct ?

**Comment by hokolomopo** [comment]
You're right, but you have to ask Kostia for the Weapon , and in you can probably merge entity and movableEntity.

**Comment by KostiaChardonnet** [comment]
If we put the movement management in `Entity` we can remove it from weapons too
